### ISSUE TITLE
Proguard task doesn't work with Google Api project

### ISSUE THREAD

**Issue by fdasoghe** [jvoegele/gradle-android-plugin#3]
I have a project with a dependency to Google Apis: it uses maps.jar (located in $ANDROID_HOME/add-ons/addon_google_apis_google_inc_7/libs).

When I run the Proguard task (both directly and as part of the whole build process), I get the error "cannot find common class of Class1 and Class2", where one of the classes is derived from class present in maps.jar.

Digging into the gradle-android-plugin I've noticed in the Proguard task code (file ProGuard.groovy, line 35) that the libraryjar parameter contains only the android.jar file.

I had no time to try a correction (I'll do today, I hope). Anyway, I think that the ProGuard task should have the whole classpath of the project, maybe of the "runtime" dependency configuration.

**Comment by jvoegele** [comment]
Digging into this issue now.  It would help to expedite the process if you could send me a minimal project that demonstrates the problem.  Thanks.

**Comment by fdasoghe** [comment]
I'm working on it, but it's not so easy. It breaks on my real Android project, but on a very simple one it works.
I'll send a not-working project as soon as possible.

**Comment by jvoegele** [comment]
Can you please send me the full build output (including stack traces) when you build with the -d (debug) flag?

i.e. gradle assemble -d

Thanks

**Comment by jvoegele** [comment]
I think the ProGuard issues have been resolved, no?

**Comment by fdasoghe** [comment]
Well, for my production project, no. I still have this issue, but I haven't time to work on. I still cannot say if the problem is in gradle-android-plugin or in proguard itself (I mean, my use of proguard).

I have to release my Android app in february, so by that time I will have to solve this issue, one way or another.

**Comment by fdasoghe** [comment]
Moving this issue to Google Code (http://code.google.com/p/gradle-android-plugin/)

**Comment by ealden** [comment]
Reopening this, as we moved back from Google Code.

**Comment by fdasoghe** [comment]
This issue is working for me, probably it could be closed.

**Comment by ealden** [comment]
Got it.  Saw your commit 5af12154c7e82a1ddc2eed51cfc0a776608a850f as well, so closing this.
